app/models/blog.py
from app import db
from datetime import datetime

class Blog(db.Model):
    __tablename__='blog'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False, index=True)
    category_id = db.Column(db.Integer, db.ForeignKey('blog_category.id', ondelete="CASCADE"), nullable=False, index=True)
    content = db.Column(db.Text, nullable=False)
    title = db.Column(db.String(150), nullable=False, unique=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    #ORM Relationships
    user = db.relationship('User', backref=db.backref('blogs', lazy="dynamic"))
    category = db.relationship('BlogCategory', backref=db.backref('blogs', lazy="dynamic"))
    
    
    
    def __repr__(self):
        return f"<blog {self.id}>"
    

app/blueprints/blog/routes.py
import os
from flask import Blueprint, render_template, request, url_for, redirect, abort, flash, get_flashed_messages
from werkzeug.utils import secure_filename
from app.utils.decorators import roles_required
from flask_login import login_required, current_user
from app.models.user import User
from app.models.blog import Blog
from app.models.comment import Comment
from app.models.category import BlogCategory
from app.models.like import Likes
from app.models.images import Image
from app import db

blog_bp = Blueprint("blog", __name__)



@blog_bp.route("/all_blogs")
@roles_required("admin", "author", "reader")
@login_required
def all_blogs():
    all_blogs = Blog.query.all()
    return render_template("blog/all_blogs.html", all_blogs=all_blogs)



@blog_bp.route("/view_blog/<int:blog_id>", methods=["GET", "POST"])
@roles_required("admin", "author", "reader")
@login_required
def view_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    comments = blog.comments
    liked = Likes.query.filter_by(user_id=current_user.id, blog_id=blog.id).first()
    images = blog.images

    if request.method == "POST":
        comment_text = request.form.get("comment", "").strip()
    
        if comment_text:
            comment = Comment(user_id=current_user.id,
                                  blog_id=blog.id,
                                  comment=comment_text)
            db.session.add(comment)
            db.session.commit()
                
            return redirect(url_for("blog.view_blog", blog_id=blog.id))
                
        else:
            flash("Entered comment is empty", "warning")
            return redirect(url_for("blog.view_blog", blog_id=blog.id))
                
                
    return render_template("blog/view_blog.html", blog=blog, comments=comments, user=current_user, liked=liked, images=images)



@blog_bp.route("/toggle_like/<int:blog_id>", methods=["POST"])
@roles_required("admin", "author", "reader")
@login_required
def toggle_like(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    liked = Likes.query.filter_by(user_id=current_user.id, blog_id=blog.id).first()
    
    if liked:
        db.session.delete(liked)
        db.session.commit()
        flash("Unliked the Blog", "info")
    else:
        new_like = Likes(user_id=current_user.id, blog_id=blog.id)
        db.session.add(new_like)
        db.session.commit()
        flash("Liked the Blog", "success")
        
    return redirect(url_for("blog.view_blog", blog_id=blog.id))
        
    

@blog_bp.route("/created_blogs")
@roles_required("admin", "author")
@login_required
def show_created_blogs():
    all_blogs = current_user.blogs.all()
    return render_template("blog/created_blogs.html", all_blogs=all_blogs, user=current_user)
    
    

UPLOAD_FOLDER = os.path.join("app", "static", "uploads")
ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@blog_bp.route("/create", methods=["GET", "POST"])
@roles_required("admin", "author")
@login_required
def create_blog():
    if request.method == "POST":
        category_id = request.form.get("category")
        blog_title = request.form.get("title")
        blog_content = request.form.get("content")
        
        
        
        selected_category = BlogCategory.query.get(category_id)
        if selected_category:
            blog = Blog(user_id=current_user.id, 
                        category_id=selected_category.id,
                        content=blog_content,
                        title=blog_title)
            
            db.session.add(blog)
            db.session.commit()
            
            images = request.files.getlist("images")
            
            
            for image_file in images:
                if image_file and allowed_file(image_file.filename):
                    filename = secure_filename(image_file.filename)
                    image_path = os.path.join(UPLOAD_FOLDER, filename)
                    image_file.save(image_path)
                    
                    relative_path = os.path.join("uploads", filename).replace('\\', '/')
                    
                    db_image = Image(blog_id=blog.id, image_path=relative_path)
                    db.session.add(db_image)
            db.session.commit()
                
            
            return redirect(url_for("blog.show_created_blogs"))
            
    return render_template("blog/create_blog.html")

app/blueprints/dashboard/routes.py
from flask import Blueprint, render_template, flash, get_flashed_messages
from flask_login import login_required, current_user
from app.utils.decorators import roles_required
from app.models.blog import Blog


dashboard_bp = Blueprint("dashboard", __name__)

@dashboard_bp.route("/dashboard")
@login_required
@roles_required("admin", "author", "reader")
def dashboard():
    all_blogs = Blog.query.all()
    flash("Login successfull!!!", "success")
    return render_template("dashboard/dashboard.html", user=current_user, all_blogs=all_blogs)

app/templates/blog/all_blogs.html
{% extends "base.html" %}


{% block title %}
    All Blogs
{% endblock %}

{% block body %}
<h2>These are the blogs available in the website!!!</h2>
    {% for blog in all_blogs %}
        <h2>{{ blog.title }}</h2>
        <p>{{ blog.content }}</p>
        <p>Author - <strong> {{ blog.user.first_name + " " + blog.user.last_name }}</strong></p>
        <strong>Comments for this blog</strong>
        {% for comment in blog.comments %}
            <p>{{ comment.comment }}</p>
            <p>By: <strong>{{ comment.user.first_name + " " + comment.user.last_name }}</strong></p>
        {% endfor %}
        <br>
        <a href="{{ url_for('blog.view_blog', blog_id=blog.id)}}">view this blog</a>
    {% endfor %}

    <br>
    <a href="{{ url_for('dashboard.dashboard') }}">click here to view dashboard</a>
{% endblock %}

app/templates/blog/create_blog.html
{% extends "base.html" %}

{% block title %}
    Create A Blog
{% endblock %}

{% block body %}
    <form action="{{ url_for('blog.create_blog') }}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

        <p>Select Blog Category: </p>
        <input type="radio" name="category" id="cat1" value=1 required="True">Wildlife</input>
        <br>
        <input type="radio" name="category" id="cat2" value=2>Biology</input>
        <br>
        <input type="radio" name="category" id="cat3" value=3>Lifestyle</input>
        <br>
        <input type="radio" name="category" id="cat4" value=4>Finance</input>
        <br>
        <input type="radio" name="category" id="cat5" value=5>Education</input>
        <br>

        <label for="title">Enter Blog Title: </label>
        <input type="text" id="title" name="title" required="True" placeholder="title">
        <br>

        <label for="content">Enter Blog Content: </label>
        <input type="text" id="content" name="content" required="True" placeholder="content goes here">
        
        <br>
        <label for="images">Upload Images: (max 3)</label>
        <br>
        <input type="file" id="images" name="images" accept="images/*">
        <br>
        <input type="file" id="images" name="images" accept="images/*">
        <br>
        <input type="file" id="images" name="images" accept="images/*">
        <br>

        <button type="submit">Submit</button>
    </form>
{% endblock %}

app/templates/blog/created_blogs.html
{% extends "base.html" %}

{% block title %}
    All Blogs
{% endblock %}

{% block body %}
<h2>These are the blogs created by you: {{ user.first_name + " " + user.last_name }}</h2>
    {% for blog in all_blogs %}
        <h2>{{ blog.title }}</h2>
        <p>{{ blog.content }}</p>
        <strong>Comments for this blog:</strong>
        {% for comment in blog.comments %}
            <p>{{ comment.comment }}</p>
            <p>By: <strong>{{ comment.user.first_name + " " + comment.user.last_name }}</strong></p>
        {% endfor %}
        <br>
        <a href="{{ url_for('blog.view_blog', blog_id=blog.id)}}">view this blog</a>
    {% endfor %}

    <br>
    <a href="{{ url_for('dashboard.dashboard') }}">click here to view dashboard</a>
{% endblock %}

app/templates/blog/view_blog.html
{% extends "base.html" %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block body %}

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <p>{{ category + " " + message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <h3>{{ blog.title }}</h3>
    <p>{{ blog.content }}</p>
    
    {% if images %}
        <h3>Images</h3>
        {% for image in images %}
    
            <img src="{{ url_for('static', filename= image.image_path  ) }}" alt="Blog Image" style="height: 5cm; width: 5cm;">
        {% endfor %}
    {% endif %}


    <p>Author: <strong>{{ blog.user.first_name + " " + blog.user.last_name }}</strong></p>
    <form action="{{ url_for('blog.view_blog', blog_id=blog.id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="comment">Add a comment to this blog:</label>
        <br>
        <textarea type="text" name="comment" id="comment" required="True" placeholder="type your comment here"></textarea>
        <br>
        <button type="submit">Submit</button>
    </form>

    <form action="{{ url_for('blog.toggle_like', blog_id=blog.id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        {% if liked %}
            <button type="submit" class="btn btn-danger">Unlike</button>
        {% else %}
            <button type="submit" class="btn btn-primary">Like</button>
        {% endif %}
        <span>{{ blog.likes.count() }} Likes </span>
    </form>

    <strong>Comments for this blog:</strong>
    {% for comment in comments %}
        <p>{{ comment.comment }}</p>
        <p>By: <strong>{{ comment.user.first_name + " " + comment.user.last_name }}</strong></p>
    {% endfor %}
    <br>
    {% set user_roles = user.roles | map(attribute='name') | list %}
    {% if 'admin' in user_roles or 'author' in user_roles or 'reader' in user_roles %}
        <a href="{{ url_for('blog.all_blogs') }}">click here to go back to all blogs</a>
    {% endif %}
    <br>
    {% if 'admin' in user_roles or 'author' in user_roles %}
        <a href="{{ url_for('blog.show_created_blogs')}}">click here to go to your blogs</a>
    {% endif %}
    <br>
        <a href="{{ url_for('dashboard.dashboard') }}">click here to view dashboard</a>
{% endblock %}